[package]
name = "axity"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0
warnings = false

[profile.release]
opt-level = 3
warnings = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
